export const borders = [
  { id: "hu-rs-Röszke 1:Horgos 1", name: "Röszke 1 - Horgos 1", openingHours: "0-24" },
  { id: "hu-rs-Röszke 2:Horgos 2", name: "Röszke 2 - Horgos 2", openingHours: "7-19" },
  { id: "hu-rs-Hercegszántó:Backi Breg", name: "Hercegszántó - Backi Breg", openingHours: "0-24" },
  { id: "hu-rs-Tompa:Kelebija", name: "Tompa - Kelebija", openingHours: "0-24" },
  { id: "hu-rs-Kübekháza:Rabe", name: "Kübekháza - Rabe", openingHours: "7-19" },
  { id: "hu-rs-Tiszasziget:Dala", name: "Tiszasziget - Dala", openingHours: "7-19" },
  { id: "hu-rs-Ásotthalom:Backi Vinogradi", name: "Ásotthalom - Backi Vinogradi", openingHours: "7-19" },
  { id: "hu-rs-Bácsalmás:Bajmok", name: "Bácsalmás - Bajmok", openingHours: "7-19" },
  { id: "hu-rs-Bácsszentgyörgy:Rastina", name: "Bácsszentgyörgy - Rastina", openingHours: "7-19" },
  { id: "rs-hu-Horgos 1:Röszke 1", name: "Horgos 1 - Röszke 1", openingHours: "0-24" },
  { id: "rs-hu-Horgos 2:Röszke 2", name: "Horgos 2 - Röszke 2", openingHours: "7-19" },
  { id: "rs-hu-Backi Breg:Hercegszántó", name: "Backi Breg - Hercegszántó", openingHours: "0-24" },
  { id: "rs-hu-Kelebija:Tompa", name: "Kelebija - Tompa", openingHours: "0-24" },
  { id: "rs-hu-Rabe:Kübekháza", name: "Rabe - Kübekháza", openingHours: "7-19" },
  { id: "rs-hu-Dala:Tiszasziget", name: "Dala - Tiszasziget", openingHours: "7-19" },
  { id: "rs-hu-Backi Vinogradi:Ásotthalom", name: "Backi Vinogradi - Ásotthalom", openingHours: "7-19" },
  { id: "rs-hu-Bajmok:Bácsalmás", name: "Bajmok - Bácsalmás", openingHours: "7-19" },
  { id: "rs-hu-Rastina:Bácsszentgyörgy", name: "Rastina - Bácsszentgyörgy", openingHours: "7-19" },
];
